lints.workspace = true

[package]
edition.workspace = true
license.workspace = true
name = "jsol-value"
rust-version.workspace = true
version.workspace = true

[dependencies]
itoa = "1"
ryu = "1"
serde.workspace = true
