lints.workspace = true

[package]
edition.workspace = true
license.workspace = true
name = "jsol-parse"
rust-version.workspace = true
version.workspace = true

[dependencies]
serde = { workspace = true, features = ["derive"] }
