lints.workspace = true

[package]
edition.workspace = true
license.workspace = true
name = "jsol-context"
rust-version.workspace = true
version.workspace = true

[dependencies]
jsol-parse = { path = "../parse" }
